src/AppBundle/Entity/Movie.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Movie
 *
 * @ORM\Table(name="movie", indexes={@ORM\Index(name="created", columns={"created"}), @ORM\Index(name="status", columns={"status"}), @ORM\Index(name="crapimg", columns={"crapimg"}), @ORM\Index(name="score", columns={"score"}), @ORM\Index(name="pubdate", columns={"pubdate"}), @ORM\Index(name="crapimg_2", columns={"crapimg"})})
 * @ORM\Entity
 */
class Movie
{
    /**
     * @var integer
     *
     * @ORM\Column(name="type", type="integer", nullable=false)
     */
    private $type = '1';

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="keywords", type="string", length=255, nullable=true)
     */
    private $keywords;

    /**
     * @var string
     *
     * @ORM\Column(name="length", type="string", length=20, nullable=true)
     */
    private $length;

    /**
     * @var string
     *
     * @ORM\Column(name="englishtitle", type="string", length=255, nullable=true)
     */
    private $englishtitle;

    /**
     * @var string
     *
     * @ORM\Column(name="cover", type="string", length=255, nullable=true)
     */
    private $cover;

    /**
     * @var string
     *
     * @ORM\Column(name="cdn_cover", type="string", length=255, nullable=true)
     */
    private $cdnCover;

    /**
     * @var string
     *
     * @ORM\Column(name="tags", type="string", length=255, nullable=true)
     */
    private $tags;

    /**
     * @var string
     *
     * @ORM\Column(name="pubdate", type="string", length=20, nullable=true)
     */
    private $pubdate;

    /**
     * @var string
     *
     * @ORM\Column(name="firstpubdate", type="string", length=20, nullable=true)
     */
    private $firstpubdate;

    /**
     * @var string
     *
     * @ORM\Column(name="kind", type="string", length=200, nullable=true)
     */
    private $kind;

    /**
     * @var string
     *
     * @ORM\Column(name="language", type="string", length=200, nullable=true)
     */
    private $language;

    /**
     * @var string
     *
     * @ORM\Column(name="country", type="string", length=200, nullable=true)
     */
    private $country;

    /**
     * @var string
     *
     * @ORM\Column(name="director", type="string", length=100, nullable=true)
     */
    private $director;

    /**
     * @var string
     *
     * @ORM\Column(name="writer", type="string", length=255, nullable=true)
     */
    private $writer;

    /**
     * @var string
     *
     * @ORM\Column(name="actor", type="text", length=65535, nullable=true)
     */
    private $actor;

    /**
     * @var string
     *
     * @ORM\Column(name="intro", type="text", length=65535, nullable=true)
     */
    private $intro;

    /**
     * @var float
     *
     * @ORM\Column(name="score", type="float", precision=10, scale=0, nullable=false)
     */
    private $score = '0';

    /**
     * @var integer
     *
     * @ORM\Column(name="hits", type="integer", nullable=false)
     */
    private $hits = '1';

    /**
     * @var string
     *
     * @ORM\Column(name="imdb", type="string", length=20, nullable=true)
     */
    private $imdb;

    /**
     * @var integer
     *
     * @ORM\Column(name="created", type="integer", nullable=true)
     */
    private $created = '0';

    /**
     * @var integer
     *
     * @ORM\Column(name="updated", type="integer", nullable=true)
     */
    private $updated = '0';

    /**
     * @var integer
     *
     * @ORM\Column(name="status", type="integer", nullable=false)
     */
    private $status = '1';

    /**
     * @var integer
     *
     * @ORM\Column(name="coming", type="integer", nullable=false)
     */
    private $coming = '0';

    /**
     * @var integer
     *
     * @ORM\Column(name="playing", type="integer", nullable=false)
     */
    private $playing = '0';

    /**
     * @var integer
     *
     * @ORM\Column(name="hot", type="integer", nullable=false)
     */
    private $hot = '0';

    /**
     * @var integer
     *
     * @ORM\Column(name="crapimg", type="integer", nullable=false)
     */
    private $crapimg = '0';

    /**
     * @var integer
     *
     * @ORM\Column(name="scheduled", type="integer", nullable=false)
     */
    private $scheduled = '0';

    /**
     * @var integer
     *
     * @ORM\Column(name="node_id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $nodeId;

    public function getId(){
        return $this->nodeId;
    }

    /**
     * Set type
     *
     * @param boolean $type
     *
     * @return Movie
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return boolean
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Movie
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set keywords
     *
     * @param string $keywords
     *
     * @return Movie
     */
    public function setKeywords($keywords)
    {
        $this->keywords = $keywords;

        return $this;
    }

    /**
     * Get keywords
     *
     * @return string
     */
    public function getKeywords()
    {
        return $this->keywords;
    }

    /**
     * Set length
     *
     * @param string $length
     *
     * @return Movie
     */
    public function setLength($length)
    {
        $this->length = $length;

        return $this;
    }

    /**
     * Get length
     *
     * @return string
     */
    public function getLength()
    {
        return $this->length;
    }

    /**
     * Set englishtitle
     *
     * @param string $englishtitle
     *
     * @return Movie
     */
    public function setEnglishtitle($englishtitle)
    {
        $this->englishtitle = $englishtitle;

        return $this;
    }

    /**
     * Get englishtitle
     *
     * @return string
     */
    public function getEnglishtitle()
    {
        return $this->englishtitle;
    }

    /**
     * Set cover
     *
     * @param string $cover
     *
     * @return Movie
     */
    public function setCover($cover)
    {
        $this->cover = $cover;

        return $this;
    }

    /**
     * Get cover
     *
     * @return string
     */
    public function getCover()
    {
        return $this->cover;
    }

    /**
     * Set cdnCover
     *
     * @param string $cdnCover
     *
     * @return Movie
     */
    public function setCdnCover($cdnCover)
    {
        $this->cdnCover = $cdnCover;

        return $this;
    }

    /**
     * Get cdnCover
     *
     * @return string
     */
    public function getCdnCover()
    {
        return $this->cdnCover;
    }

    /**
     * Set tags
     *
     * @param string $tags
     *
     * @return Movie
     */
    public function setTags($tags)
    {
        $this->tags = $tags;

        return $this;
    }

    /**
     * Get tags
     *
     * @return string
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Set pubdate
     *
     * @param string $pubdate
     *
     * @return Movie
     */
    public function setPubdate($pubdate)
    {
        $this->pubdate = $pubdate;

        return $this;
    }

    /**
     * Get pubdate
     *
     * @return string
     */
    public function getPubdate()
    {
        return $this->pubdate;
    }

    /**
     * Set firstpubdate
     *
     * @param string $firstpubdate
     *
     * @return Movie
     */
    public function setFirstpubdate($firstpubdate)
    {
        $this->firstpubdate = $firstpubdate;

        return $this;
    }

    /**
     * Get firstpubdate
     *
     * @return string
     */
    public function getFirstpubdate()
    {
        return $this->firstpubdate;
    }

    /**
     * Set kind
     *
     * @param string $kind
     *
     * @return Movie
     */
    public function setKind($kind)
    {
        $this->kind = $kind;

        return $this;
    }

    /**
     * Get kind
     *
     * @return string
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Set language
     *
     * @param string $language
     *
     * @return Movie
     */
    public function setLanguage($language)
    {
        $this->language = $language;

        return $this;
    }

    /**
     * Get language
     *
     * @return string
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Set country
     *
     * @param string $country
     *
     * @return Movie
     */
    public function setCountry($country)
    {
        $this->country = $country;

        return $this;
    }

    /**
     * Get country
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Set director
     *
     * @param string $director
     *
     * @return Movie
     */
    public function setDirector($director)
    {
        $this->director = $director;

        return $this;
    }

    /**
     * Get director
     *
     * @return string
     */
    public function getDirector()
    {
        return $this->director;
    }

    /**
     * Set writer
     *
     * @param string $writer
     *
     * @return Movie
     */
    public function setWriter($writer)
    {
        $this->writer = $writer;

        return $this;
    }

    /**
     * Get writer
     *
     * @return string
     */
    public function getWriter()
    {
        return $this->writer;
    }

    /**
     * Set actor
     *
     * @param string $actor
     *
     * @return Movie
     */

src/AppBundle/Resources/views/Page/edit.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Page edit</h1>

    {{ form(edit_form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('page') }}">
            Back to the list
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}

src/AppBundle/Resources/views/Page/index.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Page list</h1>

    <table class="records_list">
        <thead>
            <tr>
                <th>Projectid</th>
                <th>Sortid</th>
                <th>Status</th>
                <th>Id</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for entity in entities %}
            <tr>
                <td><a href="{{ path('page_show', { 'projectid': entity.id }) }}">{{ entity.projectId }}</a></td>
                <td>{{ entity.sortid }}</td>
                <td>{{ entity.status }}</td>
                <td>{{ entity.id }}</td>
                <td>
                <ul>
                    <li>
                        <a href="{{ path('page_show', { 'id': entity.id }) }}">show</a>
                    </li>
                    <li>
                        <a href="{{ path('page_edit', { 'id': entity.id }) }}">edit</a>
                    </li>
                </ul>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

        <ul>
        <li>
            <a href="{{ path('page_new') }}">
                Create a new entry
            </a>
        </li>
    </ul>
    {% endblock %}

src/AppBundle/Resources/views/Page/list.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
<style>
.bs-glyphicons-list {
    list-style: outside none none;
    padding-left: 0;
}
.bs-glyphicons li {
    font-size: 12px;
    width: 12.5%;
}
.bs-glyphicons li {
    background-color: #f9f9f9;
    border: 1px solid #fff;
    float: left;
    font-size: 10px;
    height: 115px;
    line-height: 1.4;
    padding: 10px;
    text-align: center;
    width: 115px;
}
.glyphicon{font-size:24px; font-weight: bold;}
.glyphicon-class {
    display: block;
    text-align: center;
    word-wrap: break-word;
    cursor: pointer;
}
</style>
<div id="main-container" class="main-container">
    <div class="main-content">

        <div class="page-content">
            <div class="row">
                <div class="col-md-2">

                         <ul class="ace-thumbnails clearfix">
                          
                            {% for page in pages %}                          
                                <li>
                               <div style="width:150px;height:150px;background-color:#ccc">第{{ loop.index }}页 </div>
                               <div class="tools tools-bottom">
                                              
                                                <a href="{{ path('page_list',{ 'pageid': page.id,'projectid': project.id }) }}">
                                                    <i class="ace-icon fa fa-pencil"></i>
                                                </a>

                                                <a  href="{{ path('page_remove',{ 'id': page.id }) }}">
                                                    <i class="ace-icon fa fa-times red"></i>
                                                </a>
                                            </div>
                            </li>
                            {%  endfor %}                          
                            
                         </ul>
                     <div class="bs-glyphicons">
                    <span aria-hidden="true" class="glyphicon glyphicon-plus" id="addpage"></span>
                </div>


            </div>
           

            <div class="col-md-5">
                <h3 class="row header smaller lighter purple">
                            <span class="col-sm-2"> 选择 </span>  

                            <button class="btn  ">内容 </button>
                            <button class="btn  ">图片</button>
                            <button class="btn  ">表单</button>
                        </h3> 
                    <p>
                         <input type='text' id='content'/>
       <select class="input input--dropdown js--animations" id="ani">
        <optgroup label="Attention Seekers">
          <option value="bounce">bounce</option>
          <option value="flash">flash</option>
          <option value="pulse">pulse</option>
          <option value="rubberBand">rubberBand</option>
          <option value="shake">shake</option>
          <option value="swing">swing</option>
          <option value="tada">tada</option>
          <option value="wobble">wobble</option>
        </optgroup>

        <optgroup label="Bouncing Entrances">
          <option value="bounceIn">bounceIn</option>
          <option value="bounceInDown">bounceInDown</option>
          <option value="bounceInLeft">bounceInLeft</option>
          <option value="bounceInRight">bounceInRight</option>
          <option value="bounceInUp">bounceInUp</option>
        </optgroup>

        <optgroup label="Bouncing Exits">
          <option value="bounceOut">bounceOut</option>
          <option value="bounceOutDown">bounceOutDown</option>
          <option value="bounceOutLeft">bounceOutLeft</option>
          <option value="bounceOutRight">bounceOutRight</option>
          <option value="bounceOutUp">bounceOutUp</option>
        </optgroup>

        <optgroup label="Fading Entrances">
          <option value="fadeIn">fadeIn</option>
          <option value="fadeInDown">fadeInDown</option>
          <option value="fadeInDownBig">fadeInDownBig</option>
          <option value="fadeInLeft">fadeInLeft</option>
          <option value="fadeInLeftBig">fadeInLeftBig</option>
          <option value="fadeInRight">fadeInRight</option>
          <option value="fadeInRightBig">fadeInRightBig</option>
          <option value="fadeInUp">fadeInUp</option>
          <option value="fadeInUpBig">fadeInUpBig</option>
        </optgroup>

        <optgroup label="Fading Exits">
          <option value="fadeOut">fadeOut</option>
          <option value="fadeOutDown">fadeOutDown</option>
          <option value="fadeOutDownBig">fadeOutDownBig</option>
          <option value="fadeOutLeft">fadeOutLeft</option>
          <option value="fadeOutLeftBig">fadeOutLeftBig</option>
          <option value="fadeOutRight">fadeOutRight</option>
          <option value="fadeOutRightBig">fadeOutRightBig</option>
          <option value="fadeOutUp">fadeOutUp</option>
          <option value="fadeOutUpBig">fadeOutUpBig</option>
        </optgroup>

        <optgroup label="Flippers">
          <option value="flip">flip</option>
          <option value="flipInX">flipInX</option>
          <option value="flipInY">flipInY</option>
          <option value="flipOutX">flipOutX</option>
          <option value="flipOutY">flipOutY</option>
        </optgroup>

        <optgroup label="Lightspeed">
          <option value="lightSpeedIn">lightSpeedIn</option>
          <option value="lightSpeedOut">lightSpeedOut</option>
        </optgroup>

        <optgroup label="Rotating Entrances">
          <option value="rotateIn">rotateIn</option>
          <option value="rotateInDownLeft">rotateInDownLeft</option>
          <option value="rotateInDownRight">rotateInDownRight</option>
          <option value="rotateInUpLeft">rotateInUpLeft</option>
          <option value="rotateInUpRight">rotateInUpRight</option>
        </optgroup>

        <optgroup label="Rotating Exits">
          <option value="rotateOut">rotateOut</option>
          <option value="rotateOutDownLeft">rotateOutDownLeft</option>
          <option value="rotateOutDownRight">rotateOutDownRight</option>
          <option value="rotateOutUpLeft">rotateOutUpLeft</option>
          <option value="rotateOutUpRight">rotateOutUpRight</option>
        </optgroup>

        <optgroup label="Sliding Entrances">
          <option value="slideInUp">slideInUp</option>
          <option value="slideInDown">slideInDown</option>
          <option value="slideInLeft">slideInLeft</option>
          <option value="slideInRight">slideInRight</option>

        </optgroup>
        <optgroup label="Sliding Exits">
          <option value="slideOutUp">slideOutUp</option>
          <option value="slideOutDown">slideOutDown</option>
          <option value="slideOutLeft">slideOutLeft</option>
          <option value="slideOutRight">slideOutRight</option>
          
        </optgroup>
        
        <optgroup label="Zoom Entrances">
          <option value="zoomIn">zoomIn</option>
          <option value="zoomInDown">zoomInDown</option>
          <option value="zoomInLeft">zoomInLeft</option>
          <option value="zoomInRight">zoomInRight</option>
          <option value="zoomInUp">zoomInUp</option>
        </optgroup>
        
        <optgroup label="Zoom Exits">
          <option value="zoomOut">zoomOut</option>
          <option value="zoomOutDown">zoomOutDown</option>
          <option value="zoomOutLeft">zoomOutLeft</option>
          <option value="zoomOutRight">zoomOutRight</option>
          <option value="zoomOutUp">zoomOutUp</option>
        </optgroup>

        <optgroup label="Specials">
          <option value="hinge">hinge</option>
          <option value="rollIn">rollIn</option>
          <option value="rollOut">rollOut</option>
        </optgroup>
      </select>

      <button class="butt js--triggerAnimation" onclick="addelem()">添加动画</button>
                      </p>
                 <div style="border:1px solid #ccc;height:700px;width:441px;display:block;position:absolute;" id="container"></div>
            </div>
                                        
            <div class="col-md-5">
                <h3 class="row header smaller lighter purple">
                            <span class="col-sm-3"> H5 预览</span>  

                            <button class="btn  "> 刷新</button> 
                        </h3> 
                <iframe src="{{ path('project_preview',{'id':project.id})}}" width=500 height=650 frameborder=0 id="preview" ></iframe>
            </div>


        </div>
    </div>
</div>
{% block javascripts %}
<script>
function addelem(){
    var pageid="{{page.id}}"
    var additem_url="{{ path('item_add') }}";
    var ani=$("#ani").val();
    var content=$("#content").val()
    
    if(ani){
    $("#container").append('<p class="ani" swiper-animate-effect="'+ani+'" swiper-animate-duration="0.5s" swiper-animate-delay="0.3s">'+content+'</p>');

    }else{
            $("#container").append('<p class="ani">'+content+'</p>');

    }
    $.post(additem_url,{pageid:pageid,ani:ani,content:content},function(result){


    })
}
$(document).ready(function(){
    var addpage_url="{{ path('project_addpage') }}";
    var projectid={{ project.id }};
    $('#addpage').bind('click',function(){
        $.post(
            addpage_url,{projectid:projectid},
            function(msg){
                console.log(msg);
            },'json');
    }) 
});            

</script>
{% endblock %}
{% endblock %}

src/AppBundle/Resources/views/Page/new.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Page creation</h1>

    {{ form(form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('page') }}">
            Back to the list
        </a>
    </li>
</ul>
{% endblock %}

src/AppBundle/Resources/views/Page/show.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Page</h1>

    <table class="record_properties">
        <tbody>
            <tr>
                <th>Projectid</th>
                <td>{{ entity.projectId }}</td>
            </tr>
            <tr>
                <th>Sortid</th>
                <td>{{ entity.sortid }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ entity.status }}</td>
            </tr>
            <tr>
                <th>Id</th>
                <td>{{ entity.id }}</td>
            </tr>
        </tbody>
    </table>

        <ul class="record_actions">
    <li>
        <a href="{{ path('page') }}">
            Back to the list
        </a>
    </li>
    <li>
        <a href="{{ path('page_edit', { 'id': entity.id }) }}">
            Edit
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}